version: "3"
services:
  database:
    image: "mongo"
    container_name: "typescript-mongo"
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - .env
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongo_db:/data/db
      - mongo_configdb:/data/configdb
volumes:
  mongo_db:
  mongo_configdb: